### ISSUE TITLE
Namespace "ahoy" should not be hard-coded

### ISSUE THREAD

**Issue by mciverza** [lsdopen/charts#29]
Trying to install on a namespace other than "ahoy" produces this error
```
 helm install --debug ahoy lsdopen/ahoy -n lsd-ahoy-sandbox  --values=./values.yaml 
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/mac/.cache/helm/repository/ahoy-0.9.0.tgz
<snip>
client.go:122: [debug] creating 19 resource(s)
Error: namespaces "ahoy" not found
helm.go:81: [debug] namespaces "ahoy" not found
```

Which appears to be from this config entry in the values file.
```
  sealedSecrets:
    controllerName: ahoy-sealed-secrets
    controllerNamespace: ahoy
```

**Comment by mciverza** [comment]
Even having changed that, the error persists

It could be the ArgoCD rbac entry
```
    # -- ArgoCD rbac config ([ArgoCD RBAC policy])
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
    rbacConfig:
      policy.csv: g, ahoy, role:admin
```

**Comment by mciverza** [comment]
The templates have hard-coded values too

e.g https://github.com/lsdopen/charts/blob/master/charts/ahoy/templates/keycloak-realm-configmap.yaml

They should inherit it from the values file. or Helm CLI key-value pairs

**Comment by mciverza** [comment]
in the templates, I believe this should be used instead
```
  namespace: {{ .Release.Namespace }}
 ```

For example: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ahoy-server
  name: ahoy-server
  namespace: {{ .Release.Namespace }}
  ```

**Comment by clivebor** [comment]
hey @mciverza 

We tested using {{ .Release.namespace }} in the values files and it definitely doesn't work; not sure how it would on your side, maybe you can show us.

But we've made the relevant template file changes so that they get installed in the release namespace, but the release name and namespace will still need to be changed in the values files.

We attempted to use template helpers that resolved default values based on the release name and namespace; although this doesn't work in resolving templates from dependent charts.

Therefore we took the simpler route for now.
